### ISSUE TITLE
Reason 12

### ISSUE THREAD

**Issue by xasx** [shiitake/have-some-chocolate#20]
The latest version 12.5.x can be downloaded from here:

https://a.phcdn.se/update/Stable/Reason_1250_d29-Stable-536-Win.zip

works just like the version 11: either you have an account or launch in demo mode.

**Comment by xasx** [comment]
they just updated it to version 12.5.1

https://a.phcdn.se/update/Stable/Reason_1251_d41-Stable-562-Win.zip

**Comment by shiitake** [comment]
Sorry for the late reply @xasx - I've update the package.  Thanks for the heads up with this. 🙏
