### ISSUE TITLE
textpad 8.4.1 was released on 28-May-2020

### ISSUE THREAD

**Issue by rasa** [shiitake/have-some-chocolate#4]
Downloads at https://www.textpad.com/download#TextPad841

[Release notes](https://www.textpad.com/relnotes-textpad#v841):
TextPad 8.4.1 (28-May-2020)
Issues resolved:

Polish UI and spell checker.
Improvements to the Italian UI.
Macros which did a lot of copying and pasting could be interrupted, because the clipboard could not service the requests quickly enough.
Uncommon crash opening files, reported by 2 users.
Crash doing replace all of '^' with anything, when the last line of the document is empty.
When doing replace all '^' with anything, lines following blank lines were not changed.
Crash when TextPad is forcibly closed by signing out of Windows.
Help did not link to documentation for comparing files visually.

**Comment by shiitake** [comment]
Thanks for the heads up @rasa  - I've got the package updated and waiting for moderation. 

In the meantime it should be accessible by running:  `choco install textpad --version=8.4.1`
