### ISSUE TITLE
sqlpackage 18.6 was released on 18-September-2020

### ISSUE THREAD

**Issue by BastienPerdriau** [shiitake/have-some-chocolate#6]
Downloads at https://go.microsoft.com/fwlink/?linkid=2143496

Release notes at https://docs.microsoft.com/en-us/sql/tools/release-notes-sqlpackage?view=sql-server-ver15#186-sqlpackage

**Comment by shiitake** [comment]
Thanks for the headsup @BastienPerdriau - I've pushed an update to chocolatey. Let's hope that it is approved quickly.
